# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: edik's Blog
baseurl: "" # the subpath of your site, e.g. /blog

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

plugins_dir: _plugins

# Build settings
markdown: kramdown
error_mode: strict
exclude: [README.md]

# The following settings are in a second config file:
# * email
# * url
