# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: edik's Blog

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      lang: "en-US"
      navbar: true
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: "/posts/:title.html"
  -
    scope:
      path: "internal"
    values:
      navbar: false

plugins_dir: _plugins

# Build settings
markdown: kramdown
error_mode: strict
exclude: [README.md]

# The following settings can be set in the private config file:
# * url
# * baseurl
